/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '@api/strict-http-response';
import { RequestBuilder } from '@api/request-builder';

import { ServiceResponse } from '@api/models/service-response';

export interface ApiServicesGet$Json$Params {
}

export function apiServicesGet$Json(http: HttpClient, rootUrl: string, params?: ApiServicesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ServiceResponse>>> {
  const rb = new RequestBuilder(rootUrl, apiServicesGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ServiceResponse>>;
    })
  );
}

apiServicesGet$Json.PATH = '/api/Services';
