/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiAuthAcceptInvitePost } from '../fn/auth/api-auth-accept-invite-post';
import { ApiAuthAcceptInvitePost$Params } from '../fn/auth/api-auth-accept-invite-post';
import { apiAuthLoginPost$Json } from '../fn/auth/api-auth-login-post-json';
import { ApiAuthLoginPost$Json$Params } from '../fn/auth/api-auth-login-post-json';
import { apiAuthLoginPost$Plain } from '../fn/auth/api-auth-login-post-plain';
import { ApiAuthLoginPost$Plain$Params } from '../fn/auth/api-auth-login-post-plain';
import { apiAuthMeGet$Json } from '../fn/auth/api-auth-me-get-json';
import { ApiAuthMeGet$Json$Params } from '../fn/auth/api-auth-me-get-json';
import { apiAuthMeGet$Plain } from '../fn/auth/api-auth-me-get-plain';
import { ApiAuthMeGet$Plain$Params } from '../fn/auth/api-auth-me-get-plain';
import { LoginResponse } from '../models/login-response';
import { UserResponse } from '../models/user-response';

@Injectable({ providedIn: 'root' })
export class AuthService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiAuthLoginPost()` */
  static readonly ApiAuthLoginPostPath = '/api/Auth/login';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthLoginPost$Plain()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthLoginPost$Plain$Response(params?: ApiAuthLoginPost$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<LoginResponse>> {
    const obs = apiAuthLoginPost$Plain(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthLoginPost$Plain$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthLoginPost$Plain(params?: ApiAuthLoginPost$Plain$Params, context?: HttpContext): Observable<LoginResponse> {
    const resp = this.apiAuthLoginPost$Plain$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<LoginResponse>): LoginResponse => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthLoginPost$Json()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthLoginPost$Json$Response(params?: ApiAuthLoginPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<LoginResponse>> {
    const obs = apiAuthLoginPost$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthLoginPost$Json$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthLoginPost$Json(params?: ApiAuthLoginPost$Json$Params, context?: HttpContext): Observable<LoginResponse> {
    const resp = this.apiAuthLoginPost$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<LoginResponse>): LoginResponse => r.body)
    );
  }

  /** Path part for operation `apiAuthAcceptInvitePost()` */
  static readonly ApiAuthAcceptInvitePostPath = '/api/Auth/accept-invite';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthAcceptInvitePost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthAcceptInvitePost$Response(params?: ApiAuthAcceptInvitePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = apiAuthAcceptInvitePost(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthAcceptInvitePost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthAcceptInvitePost(params?: ApiAuthAcceptInvitePost$Params, context?: HttpContext): Observable<void> {
    const resp = this.apiAuthAcceptInvitePost$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiAuthMeGet()` */
  static readonly ApiAuthMeGetPath = '/api/Auth/me';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthMeGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAuthMeGet$Plain$Response(params?: ApiAuthMeGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
    const obs = apiAuthMeGet$Plain(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthMeGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAuthMeGet$Plain(params?: ApiAuthMeGet$Plain$Params, context?: HttpContext): Observable<UserResponse> {
    const resp = this.apiAuthMeGet$Plain$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<UserResponse>): UserResponse => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthMeGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAuthMeGet$Json$Response(params?: ApiAuthMeGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
    const obs = apiAuthMeGet$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthMeGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiAuthMeGet$Json(params?: ApiAuthMeGet$Json$Params, context?: HttpContext): Observable<UserResponse> {
    const resp = this.apiAuthMeGet$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<UserResponse>): UserResponse => r.body)
    );
  }

}
