/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiAdminUsersInvitePost } from '../fn/users/api-admin-users-invite-post';
import { ApiAdminUsersInvitePost$Params } from '../fn/users/api-admin-users-invite-post';

@Injectable({ providedIn: 'root' })
export class UsersService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiAdminUsersInvitePost()` */
  static readonly ApiAdminUsersInvitePostPath = '/api/admin/users/invite';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAdminUsersInvitePost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAdminUsersInvitePost$Response(params?: ApiAdminUsersInvitePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = apiAdminUsersInvitePost(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAdminUsersInvitePost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAdminUsersInvitePost(params?: ApiAdminUsersInvitePost$Params, context?: HttpContext): Observable<void> {
    const resp = this.apiAdminUsersInvitePost$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
