/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '@api/strict-http-response';
import { RequestBuilder } from '@api/request-builder';

import { UserResponse } from '@api/models/user-response';

export interface ApiAuthMeGet$Json$Params {
}

export function apiAuthMeGet$Json(http: HttpClient, rootUrl: string, params?: ApiAuthMeGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<UserResponse>> {
  const rb = new RequestBuilder(rootUrl, apiAuthMeGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserResponse>;
    })
  );
}

apiAuthMeGet$Json.PATH = '/api/Auth/me';
