/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '@api/base-service';
import { ApiConfiguration } from '@api/api-configuration';
import { StrictHttpResponse } from '@api/strict-http-response';

import { apiHealthAdminGet } from '@api/fn/health/api-health-admin-get';
import { ApiHealthAdminGet$Params } from '@api/fn/health/api-health-admin-get';
import { apiHealthGet } from '@api/fn/health/api-health-get';
import { ApiHealthGet$Params } from '@api/fn/health/api-health-get';

@Injectable({ providedIn: 'root' })
export class HealthService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiHealthGet()` */
  static readonly ApiHealthGetPath = '/api/Health';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiHealthGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHealthGet$Response(params?: ApiHealthGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = apiHealthGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiHealthGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHealthGet(params?: ApiHealthGet$Params, context?: HttpContext): Observable<void> {
    const resp = this.apiHealthGet$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `apiHealthAdminGet()` */
  static readonly ApiHealthAdminGetPath = '/api/Health/admin';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiHealthAdminGet()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHealthAdminGet$Response(params?: ApiHealthAdminGet$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = apiHealthAdminGet(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiHealthAdminGet$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiHealthAdminGet(params?: ApiHealthAdminGet$Params, context?: HttpContext): Observable<void> {
    const resp = this.apiHealthAdminGet$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
