/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiServicesGet$Json } from '../fn/services/api-services-get-json';
import { ApiServicesGet$Json$Params } from '../fn/services/api-services-get-json';
import { apiServicesGet$Plain } from '../fn/services/api-services-get-plain';
import { ApiServicesGet$Plain$Params } from '../fn/services/api-services-get-plain';
import { ServiceResponse } from '../models/service-response';

@Injectable({ providedIn: 'root' })
export class ServicesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiServicesGet()` */
  static readonly ApiServicesGetPath = '/api/Services';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiServicesGet$Plain()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiServicesGet$Plain$Response(params?: ApiServicesGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ServiceResponse>>> {
    const obs = apiServicesGet$Plain(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiServicesGet$Plain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiServicesGet$Plain(params?: ApiServicesGet$Plain$Params, context?: HttpContext): Observable<Array<ServiceResponse>> {
    const resp = this.apiServicesGet$Plain$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<ServiceResponse>>): Array<ServiceResponse> => r.body)
    );
  }

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiServicesGet$Json()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiServicesGet$Json$Response(params?: ApiServicesGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ServiceResponse>>> {
    const obs = apiServicesGet$Json(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiServicesGet$Json$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  apiServicesGet$Json(params?: ApiServicesGet$Json$Params, context?: HttpContext): Observable<Array<ServiceResponse>> {
    const resp = this.apiServicesGet$Json$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<ServiceResponse>>): Array<ServiceResponse> => r.body)
    );
  }

}
