/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  email?: string | null;
  fullName?: string | null;
  id?: string;
  roles?: Array<string> | null;
}
