/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ServiceResponse {
  description?: string | null;
  durationMinutes?: number;
  id?: string;
  imageUrl?: string | null;
  isActive?: boolean;
  name?: string | null;
  price?: number;
}
