/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '@api/strict-http-response';
import { RequestBuilder } from '@api/request-builder';

import { InviteUserRequest } from '@api/models/invite-user-request';

export interface ApiAdminUsersInvitePost$Params {
      body?: InviteUserRequest
}

export function apiAdminUsersInvitePost(http: HttpClient, rootUrl: string, params?: ApiAdminUsersInvitePost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, apiAdminUsersInvitePost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

apiAdminUsersInvitePost.PATH = '/api/admin/users/invite';
